### ISSUE TITLE
Unable to change target temperature

### ISSUE THREAD

**Issue by iCarl** [elupus/hass_nibe#16]
When I'm trying to change the target temperature from the UI, nothing happens.
The log says:

`2019-02-02 18:05:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 289, in _handle_service_platform_call
    await func(entity, data)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/climate/__init__.py", line 574, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/nibe.py", line 237, in async_set_temperature
    scale = self.get_scale(self._adjust)
  File "/home/homeassistant/.homeassistant/custom_components/climate/nibe.py", line 146, in get_scale
    return float(data['rawValue']) / float(data['value'])
ZeroDivisionError: float division by zero`

My configuration.yaml looks like this:

`nibe:
    client_id: *******************
    client_secret: *****************
    redirect_uri: http://10.0.1.6:8123/api/nibe/auth
    writeaccess: true # set to true to support climate write (needs new tokens)

    systems:
        - system: 51460
          units:
            - unit: 0
              categories:

climate:
  - platform: nibe
    name: 'Nibe F750'
    system : 51460
    current: 40033
    target : 47398
    adjust : 47011

`

**Comment by elupus** [comment]
Odd. The value is zero. Does the current set value look correct?


PS. Dont post your secrets. With them I have access to your pump.

**Comment by iCarl** [comment]
Yes, I can read previous target temperature and current temperature.
Thanks, I edited the issue.

**Comment by iCarl** [comment]
@almirdelkic Thanks, just changed it

**Comment by iCarl** [comment]
I received a slightly different error message, without changing anything other than the auth to Nibe Uplink

`2019-02-03 21:18:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 289, in _handle_service_platform_call
    await func(entity, data)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/climate/__init__.py", line 574, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/nibe.py", line 253, in async_set_temperature
    data)
  File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/__init__.py", line 330, in put_parameter
    headers = headers,
  File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/__init__.py", line 240, in _request
    await raise_for_status(response)
  File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/__init__.py", line 74, in raise_for_status
    headers=response.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='{
  "httpStatusCode": 400,
  "errorCode": 1,
  "timestamp": "2019-02-03T21:18:50.2947218Z",
  "details": [
    "Error 15: Value out of range 47398"
  ],
  "data": null
}'`

**Comment by stphndrnd** [comment]
Tried to play with this as well and this is the error I get

`File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 289, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 574, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/climate/nibe.py", line 253, in async_set_temperature
    data)
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 330, in put_parameter
    headers = headers,
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 240, in _request
    await raise_for_status(response)
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 74, in raise_for_status
    headers=response.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='{
  "httpStatusCode": 400,
  "errorCode": 1,
  "timestamp": "2019-02-06T17:16:20.7458032Z",
  "details": [
    "Error 15: Value out of range 47398"
  ],
  "data": null
}'`

This is my config
`- platform: nibe
  name: house_thermostat
  system: !secret nibe_uplink_system
  current: 40033
  target: 47398`

What am I doing wrong? I have a premium account with WRITESYSTEM

**Comment by elupus** [comment]
Looks to be a bug there. Seems to be setting the parameter id instead of value.

I've got a new version coming up. It's not backword compatible sadly, so you need to do a new config and authorization when that is out.

I think that issue is fixed. I'll see if I perhaps could backport the fix.

**Comment by stphndrnd** [comment]
@elupus Sound good. Let us know when you have this version in this post. Happy to test and report the results.

**Comment by elupus** [comment]
can you guys turn on debug logging on the nibe components and try again? This needs to be in you homeassistant configuration.

```
logger:
    default: info
    logs:
        custom_components.nibe: debug
        custom_components.nibe.entity: debug
        custom_components.climate.nibe: debug
        nibeuplink: debug
```

**Comment by elupus** [comment]
I've fixed the devision by zero error in master of hass_nibe now

**Comment by elupus** [comment]
But the out of range error i'm not sure about.

**Comment by iCarl** [comment]
I'm still getting:

`Feb 07 17:40:09 raspberry hass[7210]:     headers=response.headers)
Feb 07 17:40:09 raspberry hass[7210]: aiohttp.client_exceptions.ClientResponseError: 400, message='{
Feb 07 17:40:09 raspberry hass[7210]:   "httpStatusCode": 400,
Feb 07 17:40:09 raspberry hass[7210]:   "errorCode": 1,
Feb 07 17:40:09 raspberry hass[7210]:   "timestamp": "2019-02-07T17:40:09.4199757Z",
Feb 07 17:40:09 raspberry hass[7210]:   "details": [
Feb 07 17:40:09 raspberry hass[7210]:     "Error 15: Value out of range 47398"
Feb 07 17:40:09 raspberry hass[7210]:   ],
Feb 07 17:40:09 raspberry hass[7210]:   "data": null
Feb 07 17:40:09 raspberry hass[7210]: }'`

**Comment by elupus** [comment]
Right, but debug info?

Den tors 7 feb. 2019 18:41 skrev iCarl <notifications@github.com>:

**Comment by iCarl** [comment]
2019-02-07 17:44:53 DEBUG (MainThread) [custom_components.climate.nibe] Set temperature on parameter 47398 to 220.0
2019-02-07 17:44:53 DEBUG (MainThread) [nibeuplink] {'timestamp': '2019-02-07T17:44:53.8310401Z', 'errorCode': 1, 'data': None, 'details': ['Error 15: Value out of range 47398'], 'httpStatusCode': 400}
2019-02-07 17:44:53 DEBUG (MainThread) [custom_components.climate.nibe] Put parameter response ERROR
2019-02-07 17:44:53 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 289, in _handle_service_platform_call
    await func(entity, data)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/climate/__init__.py", line 574, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/nibe.py", line 253, in async_set_temperature
File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/__init__.py", line 330, in put_parameter
    headers = headers,
  File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/__init__.py", line 240, in _request
    await raise_for_status(response)
  File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/__init__.py", line 74, in raise_for_status
    headers=response.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='{
  "httpStatusCode": 400,
  "errorCode": 1,
  "timestamp": "2019-02-07T17:44:53.8310401Z",
  "details": [
    "Error 15: Value out of range 47398"
  ],
  "data": null
}'

**Comment by iCarl** [comment]
Could it be that the decimal is placed in the wrong place?

**Comment by elupus** [comment]
Yup. It likely want the scaled value and not the raw value. Should be easy to fix.

**Comment by stphndrnd** [comment]
I can confirm that it should be the real/scaled value passed on to the API. See example below.

What I get in Home Assistant with debug

```
2019-02-07 17:00:40 DEBUG (MainThread) [custom_components.climate.nibe] Set temperature on parameter 47398 to 225.0
2019-02-07 17:00:41 DEBUG (MainThread) [nibeuplink] {'httpStatusCode': 400, 'errorCode': 1, 'timestamp': '2019-02-07T16:00:41.071126Z', 'details': ['Error 15: Value out of range 47398'], 'data': None}
2019-02-07 17:00:41 DEBUG (MainThread) [custom_components.climate.nibe] Put parameter response ERROR
2019-02-07 17:00:41 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 291, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 574, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/climate/nibe.py", line 253, in async_set_temperature
    data)
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 330, in put_parameter
    headers = headers,
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 240, in _request
    await raise_for_status(response)
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 74, in raise_for_status
    headers=response.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='{
  "httpStatusCode": 400,
  "errorCode": 1,
  "timestamp": "2019-02-07T16:00:41.071126Z",
  "details": [
    "Error 15: Value out of range 47398"
  ],
  "data": null
}'
```

In Postman doing a PUT https://api.nibeuplink.com/api/v1/systems/{SystemId}/parameters with the following JSON file in the body

```
{
  "settings": {
    "47398": "225.0"
  }
}
```
I get the following response

```
{
    "httpStatusCode": 400,
    "errorCode": 1,
    "timestamp": "2019-02-07T20:52:05.0114342Z",
    "details": [
        "Error 15: Value out of range 47398"
    ],
    "data": null
}
```

When I perform the same call with the following JSON

```
{
  "settings": {
    "47398": "22.5"
  }
}
```

I get the following response body

```
[
    {
        "status": "SENDING",
        "parameter": {
            "parameterId": 47398,
            "name": "47398",
            "title": "set value",
            "designation": "S1",
            "unit": "°C",
            "displayValue": "22.5°C",
            "rawValue": 225
        }
    }
]
```

Which is the correct working answer.

So we just need to set the actual temp. value in the calls to get it working.

Stupid question, but why not go with the Smart Home set of function for thermostats such as this one? https://api.nibeuplink.com/docs/v1/Api/POST-api-v1-systems-systemId-smarthome-thermostats

Thanks!

**Comment by elupus** [comment]
Smart home stuff is different. It's for if you have extra temperature sensors that you wish to use to control the heating system.

I'll probably add support for that too. But it's a different feature.

**Comment by elupus** [comment]
Should be fixed. Re-open if not.

**Comment by iCarl** [comment]
It's working! Nice work!

**Comment by stphndrnd** [comment]
Tested. I confirm it also works! Well done!
