### ISSUE TITLE
Nibe breaks after upgrade to 0.107.4 from 0.106

### ISSUE THREAD

**Issue by a94marbo** [elupus/hass_nibe#64]
Nibe failsto set up after upgrade to 0.107.4.

I only get this message in the log:

```
Logger: homeassistant.setup
Source: setup.py:128
First occurred: 17:44:49 (1 occurrences)
Last logged: 17:44:49

Unable to set up dependencies of nibe. Setup failed for dependencies: group
```

I have dowloaded the latest version with the correction for "Drop control parameter to create group"

**Comment by elupus** [comment]
Hmm. Okey, thanks that gives me a clue.

**Comment by elupus** [comment]
I think it should be solved

**Comment by a94marbo** [comment]
Nope, still fails. But no message in Notice any more.
In the logg.

```
Logger: homeassistant.config_entries
Source: custom_components/nibe/__init__.py:154
First occurred: 13:10:16 (1 occurrences)
Last logged: 13:10:16

Error setting up entry Nibe Uplink for nibe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/nibe/__init__.py", line 222, in async_setup_entry
    await async_setup_systems(hass, data, entry)
  File "/config/custom_components/nibe/__init__.py", line 162, in async_setup_systems
    config = _get_merged_config(data.config, entry)
  File "/config/custom_components/nibe/__init__.py", line 154, in _get_merged_config
    for system in entry.data[CONF_SYSTEMS].keys():
KeyError: 'systems'
```

**Comment by elupus** [comment]
You don't have a systems key in your config? So this can't have worked before?

**Comment by elupus** [comment]
Sorry no, this is my fault. I'll fix soon.

**Comment by a94marbo** [comment]
yes I have. My config lookslike this;

```
nibe:
  systems:
    - system: xxxxx
      units:
        - unit: 0
          categories: True
          statuses: True
      climates: True
      water_heaters: True
#      fans: True
```

**Comment by elupus** [comment]
upgrade again

**Comment by a94marbo** [comment]
works now. great.
